### Importing Libraries

In [3]:
import numpy as np
import threading
import os
import time
import multiprocessing

### Q1

#### Creating the matrices

In [27]:
# n = size of the square matrix
n = 5
min_val = 0
max_val = 10

A = np.random.randint(min_val,max_val,(n,n))
B = np.random.randint(min_val,max_val,(n,n))

In [28]:
print("A:\n", A)
print("B:\n", B)

A:
 [[1 8 4 2 7]
 [5 7 0 0 9]
 [0 2 8 5 1]
 [7 6 2 5 2]
 [1 2 9 1 9]]
B:
 [[8 9 4 5 4]
 [7 5 3 8 6]
 [8 0 6 5 8]
 [0 6 9 5 0]
 [0 7 2 9 1]]


##### 1. Manual Multiplication



In [29]:
# Defining the output matrix
C = [[0 for i in range(n)] for i in range(n)]

In [30]:
# For measuring the time
start = time.time()

for i in range(n):  
  for j in range(n):
    for k in range(n):
      C[i][j] += A[i][k] * B[k][j]

end = time.time()

In [31]:
C

[[96, 110, 84, 162, 91],
 [89, 143, 59, 162, 71],
 [78, 47, 101, 90, 77],
 [114, 137, 107, 136, 82],
 [94, 88, 91, 152, 97]]

In [32]:
print("Time:", end-start)

Time: 0.0005686283111572266


##### 2. MultiThreading

In [33]:
def task(min, max, A, B, C):
  for i in range(min, max):  
    for j in range(n):
      for k in range(n):
        C[i][j] += A[i][k] * B[k][j]
  
  ## Optional
  print("Task", max, " assigned to thread: {}\n".format(threading.current_thread().name)) 
  print("ID of process running task ", max, ": {}\n".format(os.getpid())) 
 
  return C

In [34]:
# Defining the output matrix
C = [[0 for i in range(n)] for i in range(n)]
C
# C = task(0, 1, A, B, C)

[[0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0]]

In [35]:
# Creating n number of threads
threads = [None] * n

In [36]:
'''
Optional
'''
# Details on thread
# threading.Thread?

'\nOptional\n'

In [37]:
# For measuring the time
start = time.time()

for i in range(n):
    threads[i] = threading.Thread(target=task, args=(i, i+1, A, B, C))
    # threads[i] = multiprocessing.Process(target=task, args=(i, i+1, A, B, C))
    threads[i].start()

for i in range(len(threads)):
    threads[i].join()

end = time.time()

Task 1  assigned to thread: Thread-4

ID of process running task  1 : 61

TaskTask 3  assigned to thread: Thread-6

ID of process running task  3 : 61

 Task2 Task4  assigned to thread: Thread-7

ID of process running task  4 : 61

 5  assigned to thread: Thread-8

ID of process running task  5 : 61

  assigned to thread: Thread-5

ID of process running task  2 : 61



In [38]:
C

[[96, 110, 84, 162, 91],
 [89, 143, 59, 162, 71],
 [78, 47, 101, 90, 77],
 [114, 137, 107, 136, 82],
 [94, 88, 91, 152, 97]]

In [39]:
print("Time:", end-start)

Time: 0.012001752853393555


##### 3. Inbuilt Library

In [40]:
matA = np.matrix(A)
matB = np.matrix(B)

# For measuring the time
start = time.time()

C = np.matmul(matA, matB)

end = time.time()

In [41]:
C

matrix([[ 96, 110,  84, 162,  91],
        [ 89, 143,  59, 162,  71],
        [ 78,  47, 101,  90,  77],
        [114, 137, 107, 136,  82],
        [ 94,  88,  91, 152,  97]])

In [42]:
print("Time:", end-start)

Time: 0.0006580352783203125


### Q2

#### Creating the array

In [112]:
# n = length of the array
n = 51
arr = np.random.randint(min_val,max_val,(n))

In [113]:
arr

array([3, 8, 9, 5, 4, 3, 7, 3, 2, 5, 8, 3, 7, 8, 2, 4, 2, 6, 0, 8, 2, 8,
       6, 9, 1, 8, 8, 7, 9, 7, 7, 2, 9, 1, 9, 6, 1, 2, 6, 5, 8, 8, 1, 1,
       6, 7, 6, 7, 4, 3, 6])

##### 1. Manual Search

In [114]:
start = time.time()

# Generating random number to be searched
search = np.random.randint(1, 10)

for i in range(n):
  if(arr[i] == search):
    print("Search: {}\nIndex: {}".format(search, i))
    break

end = time.time()

Search: 3
Index: 0


In [115]:
print("Time:", end-start)

Time: 0.000240325927734375


##### 3. Inbuilt Functions

In [117]:
ints = arr
start = time.perf_counter()
indexes = np.where(np.array(ints) == search)[0]
print(f"Item {search} found at index {indexes}")
end = time.perf_counter()
print(f"Time taken: {round(end - start, 5)} seconds(s)")

Item 3 found at index [ 0  5  7 11 49]
Time taken: 0.0008 seconds(s)


### Q3

#### Creating the array

In [47]:
# n = length of the array
n = 51
arr = np.random.randint(min_val,max_val,(n))

In [48]:
arr

array([6, 4, 9, 1, 8, 7, 5, 2, 6, 4, 1, 4, 9, 3, 1, 7, 8, 6, 0, 2, 0, 2,
       5, 6, 0, 3, 5, 8, 3, 2, 6, 1, 3, 9, 0, 6, 0, 0, 0, 0, 0, 7, 3, 4,
       2, 8, 5, 5, 7, 8, 4])

##### 1. Manual Addition

In [49]:
sum = 0

start = time.time()
for i in range(n):
    sum=sum+arr[i]

end = time.time()     
print(sum)

205


In [50]:
print("Time:", end-start)

Time: 0.0002200603485107422


##### 3. Inbuilt Function

In [60]:
start = time.time()

Sum = arr.sum()

end = time.time() 

print(Sum)

205


In [61]:
print("Time:", end-start)

Time: 0.0003330707550048828


### Q4

##### 1. Manual

In [100]:
a=[1,2]
n = int(input("Enter N (>1): "))
num_of_threads = int(input("Enter the number of threads: "))

start = time.time()

for i in range(2,n+1):
    for j in range(2,i):
        if(i%j==0):
            break
        else:
            a.append(i)
            break

end = time.time()

print(a)

Enter N (>1): 31
Enter the number of threads: 10
[1, 2, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31]


In [101]:
print("Time:", end-start)

Time: 0.00013971328735351562


##### 2. Threading

In [102]:
c=[1,2]
def prime_num_search(start,end):
    
    for i in range(start,end):
        for j in range(2,i):
            if(i%j==0):
                break
            else:
                c.append(i)
                break
    
def Thread_function():
    global num_of_threads
    thread_handle = []

    for j in range(0,num_of_threads):
        t = Thread(target = prime_num_search, args=(int((n/num_of_threads) * j),int((n/num_of_threads) * (j+1))))
        thread_handle.append(t)
        t.start()   
        
    for j in range(0,num_of_threads):
        thread_handle[j].join()
            
if __name__=="__main__":
    
    
    start = time.time()
    Thread_function()
    end = time.time()
    print(c)

[1, 2, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29]


In [103]:
print("Time:", end-start)

Time: 0.0011920928955078125
