In [62]:
import pandas as pd
import numpy as np

data = pd.read_csv("pokemon_data.xls")

In [63]:
# The imported data
data

#                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49   
1      2                Ivysaur    Grass  Poison  60      62       63   
2      3               Venusaur    Grass  Poison  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123   
4      4             Charmander     Fire     NaN  39      52       43   
..   ...                    ...      ...     ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60   
799  721              Volcanion     Fire   Water  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0         65       65     45           1      False  
1         80       80     60           1      False  
2        100      100     80           1      False  
3        122      120     80           1      False  
4         60       50     65           1      False  
..       ...      ...    ...         ...        ...  
795      100      150     50           6       True  
796      160      110    110           6       True  
797      150      130     70           6       True  
798      170      130     80           6       True  
799      130       90     70           6       True  

[800 rows x 12 columns]

In [86]:
# Making numpy arrays

hp = np.array(data['HP'])
attack = np.array(data["Attack"])
defense = np.array(data["Defense"])
sp_atk = np.array(data["Sp. Atk"])
sp_def = np.array(data["Sp. Def"])
speed = np.array(data['Speed'])

print(hp.size, attack.size, defense.size, sp_atk.size, sp_def.size, speed.size)

800 800 800 800 800 800


In [87]:
# Slicing

hp[1:5]
hp[:-780]
hp[3:10]

array([80, 39, 58, 78, 78, 78, 44], dtype=int64)

In [89]:
# Matrix

mat_1 = np.matrix([hp, attack, defense])
mat_2 = np.matrix([sp_atk, sp_def, speed])

In [94]:
print(mat_1)
print(mat_1.size)

[[ 45  60  80 ...  80  80  80]
 [ 49  62  82 ... 110 160 110]
 [ 49  63  83 ...  60  60 120]]
2400


In [93]:
print(mat_2)
print(mat_2.size)

[[ 65  80 100 ... 150 170 130]
 [ 65  80 100 ... 130 130  90]
 [ 45  60  80 ...  70  80  70]]
2400


In [92]:
# Addition

print(np.add(mat_1, mat_2))

[[110 140 180 ... 230 250 210]
 [114 142 182 ... 240 290 200]
 [ 94 123 163 ... 130 140 190]]


In [120]:
# Dot

print(np.dot(mat_1, mat_2.T))

[[4276665 4198927 3887373]
 [4938650 4734831 4602523]
 [4484027 4601707 4044450]]


In [122]:
# Sub

print(np.subtract(mat_1, mat_2))

[[-20 -20 -20 ... -70 -90 -50]
 [-16 -18 -18 ... -20  30  20]
 [  4   3   3 ... -10 -20  50]]


In [125]:
# Div

print(np.divide(mat_1, mat_2))

[[0.69230769 0.75       0.8        ... 0.53333333 0.47058824 0.61538462]
 [0.75384615 0.775      0.82       ... 0.84615385 1.23076923 1.22222222]
 [1.08888889 1.05       1.0375     ... 0.85714286 0.75       1.71428571]]
